### PR TITLE
refactor: Update Gradle wrapper

### PR DESCRIPTION
**Pull request by kmccarp**
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.gradle.UpdateGradleWrapper?organizationId=TW9kZXJuZQ%3D%3D

### CODE REVIEW

**Review by timtebeek — APPROVED** [review]

**Review by timtebeek — CHANGES_REQUESTED** [review]
Hmm we now have two folders; the parser is not at the root of this project.

**Comment by timtebeek** [comment]
Would you want me to move that parser to the root? It's become an essential part of this project but started out experimental.

**Comment by kmccarp** [comment]
This was done by running the UpdateGradleWrapper recipe -- should the behavior of that recipe change?

**Review by natedanner — APPROVED** [review]

**Comment by timtebeek** [comment]
> This was done by running the UpdateGradleWrapper recipe -- should the behavior of that recipe change?

This project is odd, but perhaps not unusual; did you use `Add if missing` in your run? I only see a link to the recipe and org, not to any variables used.

Ideally yes we fix the recipe to tolerate finding Gradle wrappers in different locations, although I'd hope not to encounter that too often.

**Comment by timtebeek** [comment]
And I'll fix this project here.

**Comment by kmccarp** [comment]
> did you use `Add if missing` in your run?

No, I didn't use `Add if missing`

**Review by timtebeek — APPROVED** [review]

**Pull request merged**
