### PR TITLE
Delete some no longer existing repos

### PR DESCRIPTION
**Pull request by knutwannheden**

### CODE REVIEW

**Review by natedanner — APPROVED** [review]

**Comment by knutwannheden** [comment]
@timtebeek Is there also some manual step involved in removing the corresponding Jenkins jobs? I got this list of repos from the console log of the latest failing build.

**Comment by timtebeek** [comment]
mod-connect has the option to delete skipped jobs, which we've enabled by default when we create the jobs.
But that assumes the rows are marked as skipped in the CSV, not removed.
https://github.com/moderneinc/mod-connect/blob/91f94ccd59012924c7ae459a023d6a35ed7b0e72/src/main/java/io/moderne/connect/commands/Jenkins.java#L173-L178

**Comment by knutwannheden** [comment]
@timtebeek So I should revert and mark them as skipped and then in a second step delete the repos from the CSV?

**Comment by timtebeek** [comment]
The workflow that creates these jobs can take an arbitrary URL; if you have some file on some branch somewhere (or even ngrok a CSV) with just the jobs you want to delete marked as skipped that's good enough.

**Pull request merged**
